"""WO111 mischief-kitten: exact-byte provenance, tool settings, bounds and factual author review handoff."""
from pathlib import Path
import json,hashlib,datetime
ROOT=Path('/home/dev/artifacts/haynes-quest/family-eras/mischief-kitten/v001')
SOURCE=Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
digest=sha(ROOT/'mischief-kitten.glb')
construction=json.loads((ROOT/'construction.json').read_text())
three=json.loads((ROOT/'three-inspection.json').read_text())
browser=json.loads((ROOT/'final-preview/browser-inspection.json').read_text())
validation=json.loads((ROOT/'validation.json').read_text())
attachments=json.loads((ROOT/'attachment-inspection.json').read_text())
for report in [three,browser,validation,attachments]:
 assert report.get('glb_sha256',report.get('sha256'))==digest
 assert all(report['checks'].values())
assert construction['files']['mischief-kitten.glb']['sha256']==digest
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
common={'work_order':'WO111','asset_id':'mischief-kitten','version':'v001','created_utc':now,'glb_sha256':digest,'candidate_status':"Awaiting Tom's review · used in the family release"}
attack=next(c for c in construction['clips'] if c['name']=='attack')
defeat=next(c for c in construction['clips'] if c['name']=='defeat')
provenance={**common,
 'authoring_agent':'Claude Opus 5.5 (claude-opus-5-5, xhigh) Blender author under the PLAN-019 coordinator; Tom ruled on Sept 26 that Claude Opus 5.5 does the WO111 Blender work',
 'authoring_tool':'Blender MCP execute_blender_code on the second isolated authoring service (blender-authoring-2), driven by a small streamable-HTTP JSON-RPC client (source/transfer.py)',
 'blender_version':construction['blender_version'],
 'source_reference':{'kind':'Blender reference sheet, no generated concept','file':'reference-sheet.png','sha256':sha(ROOT/'reference-sheet.png'),'notes':'reference-notes.md','notes_sha256':sha(ROOT/'reference-notes.md'),
  'blockout_master':'mischief-kitten-blockout.blend','blockout_sha256':sha(ROOT/'mischief-kitten-blockout.blend'),
  'coordinator_review':'Approved Sept 26 (SHEET-REVIEWS.md): keep the mini stovepipe hat, gadget pack, bell collar and question-mark tail; pounce attack.',
  'generator':'None. The sheet is a Cycles render of a procedural Blender blockout; no image-generation model was used for this asset.'},
 'source_scripts':{p.name:sha(p) for p in sorted(SOURCE.iterdir()) if p.suffix in ['.py','.mjs','.json'] and p.is_file()},
 'original_work':['Final topology, UVs, weights, the 32-bone quadruped rig and all five clips are new; the blockout supplied measured proportions, colours and parody hooks only.','Original deterministic 1024 palette atlas generated in Blender Python from the sheet colours; tabby back stripes and the cream belly are bisected face bands, the crown stripes thin painted ribbons, no external texture.','Mesh, UV, IK, transfer and validation utilities adapted from the WO111 rival-mayor, gadget-helper and honk-bus authoring scripts.'],
 'excluded_inputs':['No family photos, names, birthdays or likenesses.','No copied franchise names, models, faces, logos, badges, costumes, lettering, recordings or textures; the collar carries a plain bell and the pack no emblem.'],
 'rights_note':'Original authored study. No exclusive-rights or franchise-endorsement claim.',
 'scope':'Technical candidate delivery. The coordinator owns catalog publication and runtime integration; the owner exact-version and physical-device review remain open.'}
settings={**common,
 'blender':{'version':construction['blender_version'],'instance':'blender-authoring-2','units':'METRIC','unit_scale':1,'authoring_axes':'+Z up / +Y forward (character right = +X)','frames_per_second':30,'animation_mode':'NLA_TRACKS','skin':'One skin; rigid props plus two-weight smoothstep blends at the shoulders, elbows, hips, knees, the body midline, the haunches, the tail chain and the antenna','root':'Identity, fixed floor-centred root; no root animation; the hips translate for the bob, the pounce travel (returns by the end) and the seated defeat','bind_pose':'Four paws down with the sheet tail curl, as the sheet notes suggest; IK controls at rest reproduce it (max matrix error %.1e). The sheet tiptoe is idle at 0 s.'%construction['rest_reproduction_max_error']},
 'export':{'format':'GLB','axes':'+Y up / -Z forward','selection_only':True,'materials':2,'texture':{'file':'pigment.png','width':1024,'height':1024,'embedded':True},'no_external_resources':True,'no_required_extensions':True,'compression':'None; no Draco, Meshopt or KTX2 requirement'},
 'preview':{'source':'Exact delivered GLB via Three.js GLTFLoader','three_revision':three['three_revision'],'browser':browser['browser'],'renderer':browser['renderer'],'viewport_px':[800,900],'orthographic_camera':{'left':-.62,'right':.62,'top':.6975,'bottom':-.6975,'target':[0,.44,0],'views':{'front':[0,.44,-8],'side':[8,.44,0],'back':[0,.44,8],'threequarter':[5.657,.44,-5.657],'beauty':[4.1,3.0,-7.4]}},'main_stills':'idle clip at 0 s (the sheet tiptoe); rest-*.png are the bind pose','lighting':'Warm hemisphere plus three directional lights; ACES tone mapping exposure 1.0','scales':[1,.35],'no_physical_device_claim':True},
 'checks':{'khronos_zero_errors_warnings':True,'exact_three_adapter_all_checks':True,'chromium_all_clips_normal_small':True,'source_attachment_checks':True}}
visual={**common,
 'author_review':'Exact-export front, side, back and three-quarter stills (idle at 0 s, the sheet tiptoe) compared with the reference sheet at the same angles and metric scale (sheet-vs-export.png); rest-pose stills; five-clip normal/small motion sheet; attack front/side windup-leap-contact-recovery and 35% gameplay-scale strip; held defeat front/side/three-quarter/beauty inspected.',
 'coordinator_review':'Pending PLAN-019 coordinator intake. Not Tom approval.','owner_review':'Pending exact-version decision',
 'sheet_matching':['Silhouette kept from the approved blockout at its measured coordinates: oversized round head, straight right ear and cocked left ear, mini plum stovepipe hat tipped to its left (0.9187 m top, the blockout height), whiskers 0.60 m across, bean body with bunched haunches, cream bib, socks and mitten paws, question-mark tail swung up on its right with a cream tip.','Face as on the sheet: big honey eyes glancing to its right with two highlights, raised right brow, sly squint and slanted brow on the left, cream muzzle with a lopsided smirk and a tongue blep, pink nose; plum-lilac crown, cheek, back, haunch and tail-ring stripes.','Kit as on the sheet: raspberry collar with a honey bell, teal gadget pack with a raspberry button, honey dial, brass rivets, straps, a brass spring antenna, honey ball and tiny cream propeller.','Colours are the sheet hex values exactly (atlas palette); the preview renders them slightly deeper than the Cycles Standard-view sheet because of its ACES tone mapping and three-light rig.','Idle starts in the sheet tiptoe: right forepaw raised and curled with pink toe beans facing forward.'],
 'author_corrections':['First assembled pass was 15,886 triangles; the crown-stripe bisect cuts alone added about 1,000 to the head. The crown stripes became thin surface ribbons and the tail, leg, collar, strap, antenna and brim ring counts were reduced (14,142); smoother ears and tucked toe beans give the final 14,174.','The crouch and landing first pitched the chest nose-up (axis sign error), so the contact read as standing; corrected to chest down, rump up and face low over the paws.','Ear axes corrected: the hit now flattens the ears back and the defeat droops them outward.','First defeat sit sank the folded thighs 41 mm below the floor; the seat was raised until the Blender and 60 Hz checks both clear.','The blockout pack sat 3.6 cm inside the back of the head; the pack moved 4 cm back and tilts back during the crouch and hit, so the head never enters it.','The idle left-ear twitch clipped the tilted hat brim (now an outward flick), and the defeat hat slide passed through that ear (it now hops over).','The defeat hat first slid behind the head; its held placement is now computed from the head surface over the left eye.','The limp defeat tail first rose into the head, then crossed the right hind leg; its flat-on-the-floor pose came from a clearance search against the floor, the head and the hind legs.','The bottom wiggle first ran at 8.75 Hz (aliased at 30 fps) and 60 Hz sampling found inter-key paw dips up to 4.3 mm; the wiggle was slowed to about 4.8 Hz and all paws got a 3 mm sole clearance (the rival mayor uses 4 mm).','Front toe beans peeked out as a pink sliver under the planted paws; they were tucked in from the sole edge.'],
 'deviations_from_sheet_notes':['Bind pose is four paws down (the sheet notes suggestion); the sheet tiptoe is recreated at idle 0 s, and the main stills show it.','The pack sits 4 cm further back than the blockout so it clears the head.','Defeat follows the work-order brief, "tumbles and sits dizzy, held": knocked up into a spinning tumble, it plops down seated with a dizzy head wobble, drooped ears, the hat over its left eye and the tail limp on the floor. The sheet notes had suggested rolling onto its back.','Paws float 3 mm above the floor (sole clearance) so interpolated frames never dip below it.','Toe beans are on the front paws only (the sheet shows them on the raised forepaw); the hind paws keep the sheet toe grooves.'],
 'dimensions_width_height_depth_m':three['dimensions_m'],'rest_bounds_y_up':three['rest_bounds_y_up'],'animated_bounds_y_up':three['all_animation_bounds_y_up'],'stored_safe_culling_bounds':three['exported_safe_bounds_y_up'],
 'contact_seconds':attack['contact_time_s'],'attack_duration_seconds':attack['duration_s'],'defeat_held_from_seconds':defeat['held_final_pose_from_s'],
 'attack_beats':{'crouch_s':[0.12,0.88],'bottom_wiggle_s':[0.50,0.92],'airborne_leap_s':[0.92,1.25],'airborne_peak_s':1.07,'contact_s':1.25,'belly_flop_squash_s':[1.20,1.60],'hop_back_s':[1.56,1.84],'back_on_its_spot_s':1.84},
 'defeat_held':three['defeat_held'],'no_floor_penetration':three['checks']['no_floor_penetration'],
 'limitations':['Headless software Chromium is not physical Safari or hardware performance acceptance.','The attachment audit tests listed part pairs every frame on the source scene; it is not a universal triangle-collision proof. Intended contacts (leg roots inside the body and haunches, the collar around the head, the pack and straps on the back, the hat on the head) are not tested.','In the game the windup phase scrubs the attack clip from 0 to the 1.25 s contact, so the crouch, wiggle and leap play at the simulation windup speed.','The pounce carries the body 0.30 m forward through the hips and brings it back by 1.84 s; the root never moves.','Owner final-art review and runtime integration are separate from this authoring handoff.']}
bounds={**common,'method':three['method'],'rest_bounds_y_up':three['rest_bounds_y_up'],'dimensions_width_height_depth_m':three['dimensions_m'],'height_m':three['height_m'],'sole_clearance_m':three['sole_clearance_m'],'body_footprint_y_up':three['body_footprint_y_up'],'all_animation_bounds_y_up':three['all_animation_bounds_y_up'],'safe_culling_envelope_y_up':three['exported_safe_bounds_y_up'],'defeat_held_hips_height_m':three['defeat_held']['hips_height_m'],'note':'glTF axes: +Y up, character faces -Z; its right (the tail side) is +X. Root at the floor origin under the body centre.'}
for name,record in [('provenance.json',provenance),('tool-settings.json',settings),('visual-review.json',visual),('bounds.json',bounds)]:
 (ROOT/name).write_text(json.dumps(record,indent=2)+'\n')
print(json.dumps({'glb_sha256':digest,'reports':['provenance.json','tool-settings.json','visual-review.json','bounds.json'],'all_technical_checks':True}))
