"""WO111 radio-host-showman: exact-byte provenance, tool settings, bounds and factual author review handoff.
Adapted from the demon-band-idol v001 make-evidence.py. Run after the final fetch, inspect-three, preview and compare."""
from pathlib import Path
import json,hashlib,datetime
ROOT=Path('/home/dev/artifacts/haynes-quest/family-eras/radio-host-showman/v001')
SOURCE=Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
digest=sha(ROOT/'radio-host-showman.glb')
construction=json.loads((ROOT/'construction.json').read_text())
three=json.loads((ROOT/'three-inspection.json').read_text())
browser=json.loads((ROOT/'final-preview/browser-inspection.json').read_text())
validation=json.loads((ROOT/'validation.json').read_text())
attachments=json.loads((ROOT/'attachment-inspection.json').read_text())
for report in [three,browser,validation,attachments]:
 assert report.get('glb_sha256',report.get('sha256'))==digest
 assert all(report['checks'].values())
assert construction['files']['radio-host-showman.glb']['sha256']==digest
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
common={'work_order':'WO111','asset_id':'radio-host-showman','version':'v001','created_utc':now,'glb_sha256':digest,'candidate_status':"Awaiting Tom's review · used in the family release"}
attack=next(c for c in construction['clips'] if c['name']=='attack')
defeat=next(c for c in construction['clips'] if c['name']=='defeat')
provenance={**common,
 'authoring_agent':'Claude Opus 5.5 (claude-opus-5-5, xhigh) Blender author under the PLAN-019 coordinator; Tom ruled on Sept 26 that Claude Opus 5.5 does the WO111 Blender work',
 'authoring_tool':'Blender MCP execute_blender_code on the primary authoring service (blender-authoring, instance 1), driven by a small streamable-HTTP JSON-RPC client (source/mclient.py, source/author_run.py)',
 'blender_version':construction['blender_version'],
 'source_reference':{'kind':'Blender reference sheet, no generated concept','file':'reference-sheet.png','sha256':sha(ROOT/'reference-sheet.png'),'notes':'reference-notes.md','notes_sha256':sha(ROOT/'reference-notes.md'),
  'blockout_master':'radio-host-showman-blockout.blend','blockout_sha256':sha(ROOT/'radio-host-showman-blockout.blend'),
  'coordinator_review':'Approved Sept 26 (SHEET-REVIEWS.md): slicked hair with two tufts, a huge showman grin, a candy-stripe jacket, a bow tie and a vintage broadcast mic on a cane; subtle warm rim or brass highlights so he reads in the Rat Casino dim light. Revised model notes after Tom\'s Sept 26 ruling (DESIGN-027: scary is welcome, no gore): a too-wide grin with sharp teeth, eyes that glow red in the dark (emissive), a faint static halo; attack a mic-cane swing with a radio-static burst; defeat a jerky, glitchy bow frozen mid-grin, held.',
  'generator':'None. The sheet is a Cycles render of a procedural Blender blockout; no image-generation model was used for this asset.'},
 'source_scripts':{p.name:sha(p) for p in sorted(SOURCE.iterdir()) if p.suffix in ['.py','.mjs','.json','.sh'] and p.is_file()},
 'original_work':['Final topology, UVs, weights, 28-joint rig and all five clips are new; the approved blockout supplied measured proportions, colours, parody hooks and the sheet-pose coordinates (cane, fist, waving glove, feet) only.',
  'Original 1024 painted atlas generated with numpy in Blender Python (paint.py): the creepier face (hollow sockets, heavy lids, high brows, too-wide sharp-toothed grin), the candy-stripe jacket map with shirt, lapels, brass piping, cutaway, pocket welt, lapel pin, back belt and vent, the glowing iris, the mic grille bands and flat sheet-colour and glow tiles. No external texture.',
  'Mesh, UV, transfer, validation and evidence utilities adapted from the WO111 demon-band-idol / rival-mayor / gadget-helper scripts.'],
 'excluded_inputs':['No family photos, names, birthdays or likenesses.','No copied franchise names, models, faces, logos, costumes, lettering, recordings or textures. No dial pupils, antlers, horns or demon sigils: the tufts stay hair, the pupils are plain pinpricks.'],
 'rights_note':'Original authored study. No exclusive-rights or franchise-endorsement claim.',
 'scope':'Technical candidate delivery. The coordinator owns catalog publication and runtime integration; the owner exact-version and physical-device review remain open.'}
settings={**common,
 'blender':{'version':construction['blender_version'],'instance':'blender-authoring (instance 1, primary)','units':'METRIC','unit_scale':1,'authoring_axes':'+Z up / +Y forward (character right = +X)','frames_per_second':30,'animation_mode':'NLA_TRACKS','animation_keys':'Every frame, linear, exported without keyframe optimisation',
  'skin':'One skin; rigid props plus smoothstep blends at the neck, waist, shoulders, elbows, hips, knees, ankles and tuft chains (at most %d influences used)'%three['max_skin_influences'],
  'root':'Identity, fixed floor-centred root; no root animation; the hips carry the bounce, lean, lunge and bow',
  'bind_pose':'Right arm in the sheet A-pose holding the planted cane (the sheet pose), left arm its mirror, head straight, feet toed out 12 deg (rest controls reproduce it, max matrix error %.1e)'%construction['rest_reproduction_max_error'],
  'sheet_pose':'Idle at 0 s reproduces the blockout sheet pose (cane tip, grip, mic centre, waving wrist and ankles within %.1e m)'%max(construction['sheet_pose_reproduction_m'].values())},
 'export':{'format':'GLB','axes':'+Y up / -Z forward','selection_only':True,'materials':2,'glow_material':'Principled BSDF with the atlas linked to both Base Color and Emission Color, Emission Strength 1.0 (glTF emissiveTexture = the same image, emissiveFactor [1,1,1]; no KHR_materials_emissive_strength)','texture':{'file':'pigment.png','width':1024,'height':1024,'embedded':True},'no_external_resources':True,'no_required_extensions':True,'compression':'None; no Draco, Meshopt or KTX2 requirement'},
 'preview':{'source':'Exact delivered GLB via Three.js GLTFLoader','three_revision':three['three_revision'],'browser':browser['browser'],'renderer':browser['renderer'],'viewport_px':[800,900],'orthographic_camera':{'left':-1.25,'right':1.25,'top':1.40625,'bottom':-1.40625,'target':[0,1.05,0],'views':{'front':[0,1.05,-8],'side':[8,1.05,0],'back':[0,1.05,8],'threequarter':[5.657,1.05,-5.657],'beauty':[4.2,2.9,-7.6]}},'stills_pose':'Main stills: idle at 0 s (the sheet pose); rest-*.png: the bind pose; dark-*.png: a dim casino-room rig (hemisphere 0.12, key lights at 5%) to show the emissive eyes, bulb, halo and burst','lighting':'Warm hemisphere plus three directional lights; ACES tone mapping exposure 1.0','scales':[1,.35],'no_physical_device_claim':True},
 'checks':{'khronos_zero_errors_warnings':True,'exact_three_adapter_all_checks':True,'chromium_all_clips_normal_small':True,'source_attachment_checks':True}}
visual={**common,
 'author_review':'Exact-export front, side, back and three-quarter stills (idle at 0 s = the sheet pose) compared with the reference sheet at the same angles and metric scale (sheet-vs-export.png); rest-pose stills; dark-room glow stills; five-clip normal/small motion sheet; attack front/side windup-sweep-contact-recovery and the 35% gameplay-scale strip; held defeat front/side/three-quarter/beauty; close-ups of the face, lapels, collar, both wrists through the swing, the tufts and the bow.',
 'coordinator_review':'Pending PLAN-019 coordinator intake. Not Tom approval.','owner_review':'Pending exact-version decision',
 'sheet_matching':['Silhouette kept from the approved blockout at its measured coordinates: two asymmetric wispy hair tufts (the right one fuller) on a slicked auburn cap with sideburn tabs, a big round head tilted 4 deg toward the mic in the sheet pose, the big black bow tie, the red/cream candy-stripe jacket (the blockout\'s 24 stripes by lathe angle) with the black shawl collar, two brass buttons, the honey pocket square, the lapel pin and the rounded cutaway, striped sleeves with black cuffs and white gloves, long black trousers with the red side stripe, cream-and-black spectator shoes toed out 12 deg, the back half-belt with brass buttons and the vent, and the tall black cane topped by the silver broadcast mic in its brass yoke with the on-air bulb, planted in his right fist while the left glove waves.',
  'Idle at 0 s reproduces the sheet pose exactly: cane tip, grip and mic centre within 1e-6 m of the blockout, the waving wrist and both ankles likewise.',
  'Colours are the sheet hex values (atlas); the brass lapel piping, rim and button highlights answer the sheet review\'s request for brass highlights that read in dim light. The preview renders colours slightly deeper than the Cycles Standard-view sheet because of its ACES tone mapping.',
  'Pushed creepier per the revised notes: the grin is 17% wider than the sheet (half-width 0.138 vs 0.118 m head-local) with a row of sharp upper and lower teeth; hollow shadowed sockets, heavy lids and pale eye whites; red irises with pinprick pupils on separate shells of the glow material, so they glow in the dark; the on-air bulb glows; a faint broken zigzag static halo (dim red with three pale arcs) floats behind the head; a radio-static starburst pops open round the mic at the attack contact. No blood, gore, horns, dial pupils or sigils.'],
 'author_corrections':['The idle head tick first rolled the head into the mic capsule; it now snaps away from the mic and turns to the audience.',
  'At the first contact pose the mic head covered his face in the player\'s view; contact now brings the mic in at chest height on his right so the grin stays visible.',
  'The static burst first radiated in a plane containing the cane axis, which points at the player at contact, so it was edge-on and invisible from the front; it now radiates across the cane axis as a starburst facing the player, with bolder bolts (0.90 m across when open).',
  'The opening cane twirl was invisible at play distance; the cane now lifts 18 cm and tips out as it twirls, with a heel click.',
  'The blockout shirt collar (rim at 1.523 m, with a capping disc) sat inside the jaw in every frame; it is now an open ring with its rim at 1.485 m, the black shawl collar band sits 1.1 cm lower, and the neck carries a painted white collar band under the chin so the sheet\'s white collar still reads.',
  'A full propeller spin of the bow tie swept the wings into the chin; the bow tie now wobbles up to 0.42 rad (clearance measured at 0.5).',
  'On the downswing the cane shaft clipped the right upper arm; the elbow now rises out to the side for the sweep.',
  'In the bow the left hand first hit the left thigh; it now settles in front of the belly, carried by the spine.',
  'When the head snaps up in the held bow the halo dropped into the shoulders; it now counter-tilts 0.38 rad (a probe found -0.30 to -0.45 clear), and the left tuft flops forward instead of back into the halo.',
  'The held bow first pitched the face 29 deg down; the head snap was raised, then limited to a net 0.5 rad neck+head extension because more pushed the jaw into the collar (probe_defeat.py). The bow eased to %.0f deg chest pitch so the face still comes up (%.0f deg below level).'%(three['defeat_held']['chest_pitch_forward_deg'],-three['defeat_held']['head_forward_pitch_deg']),
  'The defeat shudder could dip the planted cane tip 1.8 mm below the floor; its jolts now only lift.',
  'The raised lapel shells\' side walls sampled the jacket paint across the shirt edge and looked like a zipper; they now use flat ink with a brass outer rim.',
  'Sharper brows were first raised under the hairline; they are back at the blockout heights with a sharper outer flick.'],
 'deviations_from_sheet_notes':['The sheet notes describe a friendly, never-scary showman; the revised model notes after Tom\'s Sept 26 ruling (DESIGN-027) supersede that: the model is genuinely creepy (grin, teeth, glowing eyes, static halo and burst) with no gore.',
  'Attack follows the revised note "a mic-cane swing with a radio-static burst" with a showy lean: twirl and heel click (0-0.28 s), wind-up leaning back with the mic raised back over his right shoulder and the free hand flared (0.28-0.94 s), an overhead sweep and lunge that brings the mic in at chest height at the 1.25 s contact while the static starburst pops open, a vibrato hold, a quick bow and back to the planted cane by 2.0 s. The sweep is overhead because the fist grips the 1.7 m cane 1.03 m up its shaft: a flat horizontal sweep drives the long lower end through his body.',
  'Defeat follows the revised note "a jerky, glitchy bow, frozen mid-grin, held" instead of the sheet notes\' sit-down: a stepped-jolt shudder (jolts change every two frames), a bow that lands in seven stutter steps while he leans on the planted cane, the free arm across the waist, then the head snaps up and cocks toward the player with the eyes stuck wide and the halo askew; held from %.3f s.'%defeat['held_final_pose_from_s'],
  'Bind pose: the notes ask for an A-pose; the sheet\'s right arm already hangs in that A-pose with the fist on the planted cane, so the right arm binds in the sheet pose (the cane stays planted in the bind pose); the left arm binds as its mirror and the wave is recreated in idle.',
  'Eye acting: a scale bone per eye (as the notes suggest) scales the glowing iris shells; the painted eye whites and the permanent grin do not change.',
  'Rig (28 joints): root, hips, spine, chest, neck, head, two eye bones, two two-bone tuft chains, the halo, the bow tie, three-bone arms, the cane (child of the right hand) with its burst bone, thigh/shin/foot legs.',
  'Height: %.3f m in the bind pose (tufts and halo top), %.3f m in the sheet pose; the brief asks about 2.0 m, above the WO111 ordinary band of 0.8-1.4 m, as the sheet notes flagged for the coordinator.'%(three['height_m'],three['sheet_pose']['idle0_top_m'])],
 'dimensions_width_height_depth_m':three['dimensions_m'],'rest_bounds_y_up':three['rest_bounds_y_up'],'animated_bounds_y_up':three['all_animation_bounds_y_up'],'stored_safe_culling_bounds':three['exported_safe_bounds_y_up'],
 'sheet_pose_height_m':three['sheet_pose']['idle0_top_m'],'contact_seconds':attack['contact_time_s'],'attack_duration_seconds':attack['duration_s'],'windup_seconds':attack['windup_s'],'burst_open_seconds':attack['burst_open_s'],'defeat_held_from_seconds':defeat['held_final_pose_from_s'],
 'defeat_held':three['defeat_held'],'defeat_bow_stutter':three['animations']['defeat']['bow_stutter'],'no_floor_penetration':three['checks']['no_floor_penetration'],
 'limitations':['Headless software Chromium is not physical Safari or hardware performance acceptance.','The attachment audit tests listed part pairs every frame on the source scene; it is not a universal triangle-collision proof. Intended contacts (the fist round the cane, glove cuffs in the sleeve ends, sleeve roots in the jacket, trouser tops in the jacket and seat, the tuft roots in the hair cap, the iris shells on the face, the neck inside the collar) are not tested.',
  'In the game the windup phase scrubs the attack clip from 0 to the 1.25 s contact, so the twirl, wind-up and sweep play at the simulation windup speed; the burst opens from 1.18 s and closes by 1.60 s.',
  'Runtime culling: the wind-up raises the mic to %.2f m and the open burst reaches %.2f m from the capsule centre; three.js computes a skinned bounding sphere once, so the coordinator should apply the stored safe envelope (skin extras model_space_bounds_y_up), as filed in haynes-quest issue #103.'%(three['all_animation_bounds_y_up']['max'][1],three['animations']['attack']['max_burst_reach_m']),
  'The glow material uses the atlas as emission at factor 1, so the glowing parts read as bright red in lit rooms too; the eyes, bulb, halo and burst always glow (the scare-scene blackouts dim scenery practicals, not characters).',
  'The painted face cannot change expression; the grin holds in every clip by design.','Owner final-art review and runtime integration are separate from this authoring handoff.']}
bounds={**common,'method':three['method'],'rest_bounds_y_up':three['rest_bounds_y_up'],'dimensions_width_height_depth_m':three['dimensions_m'],'height_m':three['height_m'],'sheet_pose_height_m':three['sheet_pose']['idle0_top_m'],'sole_clearance_m':three['sole_clearance_m'],'body_footprint_y_up':three['body_footprint_y_up'],'all_animation_bounds_y_up':three['all_animation_bounds_y_up'],'safe_culling_envelope_y_up':three['exported_safe_bounds_y_up'],'defeat_held_hips_height_m':three['defeat_held']['hips_height_m'],'note':'glTF axes: +Y up, character faces -Z; his right hand (the cane) is +X. Root at the floor origin under the body centre. The rest width is set by the planted cane (+X) and the lowered open left glove (-X); the sheet pose spans the cane to the waving glove.'}
for name,record in [('provenance.json',provenance),('tool-settings.json',settings),('visual-review.json',visual),('bounds.json',bounds)]:
 (ROOT/name).write_text(json.dumps(record,indent=2)+'\n')
print(json.dumps({'glb_sha256':digest,'reports':['provenance.json','tool-settings.json','visual-review.json','bounds.json'],'all_technical_checks':True}))
