"""WO111 web-slinger-helper: exact-byte provenance, tool settings, bounds and the factual author review handoff.
Adapted from the demon-band-idol v001 make-evidence.py. Run after delivery.py fetch, the final inspect-three,
preview and compare (their outputs copied into the durable directory)."""
from pathlib import Path
import json,hashlib,datetime
ROOT=Path('/home/dev/artifacts/haynes-quest/family-eras/web-slinger-helper/v001')
SOURCE=Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
digest=sha(ROOT/'web-slinger-helper.glb')
construction=json.loads((ROOT/'construction.json').read_text())
three=json.loads((ROOT/'three-inspection.json').read_text())
browser=json.loads((ROOT/'final-preview/browser-inspection.json').read_text())
validation=json.loads((ROOT/'validation.json').read_text())
attachments=json.loads((ROOT/'attachment-inspection.json').read_text())
for report in [three,browser,validation,attachments]:
 assert report.get('glb_sha256',report.get('sha256'))==digest
 assert all(report['checks'].values())
assert construction['files']['web-slinger-helper.glb']['sha256']==digest
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
common={'work_order':'WO111','asset_id':'web-slinger-helper','version':'v001','role':'friendly helper (DESIGN-013): heals the player, never an enemy','created_utc':now,'glb_sha256':digest,'candidate_status':"Awaiting Tom's review · used in the family release"}
clip=lambda n:next(c for c in construction['clips'] if c['name']==n)
attack,defeat,hit=clip('attack'),clip('defeat'),clip('hit')
dh=three['defeat_held'];rt=three['friendly_runtime'];sp=three['sheet_pose']
provenance={**common,
 'authoring_agent':'GPT-6 Astra (gpt-6-astra, max), fresh WO111 Blender author on September 29. Approved reference sheet and unfinished source checkpoint were authored by Claude Opus 5.5 and are preserved separately.',
 'authoring_tool':'Blender MCP execute_blender_code on the primary authoring service, instance 1 (blender-authoring), driven by a small streamable-HTTP JSON-RPC client (source/transfer.py). Instance 2 (blender-authoring-2) was not touched.',
 'blender_version':construction['blender_version'],
 'source_reference':{'kind':'Blender reference sheet, no generated concept','file':'reference-sheet.png','sha256':sha(ROOT/'reference-sheet.png'),'notes':'reference-notes.md','notes_sha256':sha(ROOT/'reference-notes.md'),
  'blockout_master':'web-slinger-helper-blockout.blend','blockout_sha256':sha(ROOT/'web-slinger-helper-blockout.blend'),
  'coordinator_review':'Approved Sept 26 (SHEET-REVIEWS.md): a friendly masked kid hero with a dew-drop web hood, a star emblem, a domino mask, heart-button web-shooters and a web-rope coil. Clearly friendly and distinct from enemies. Friendly clips per DESIGN-013 and the set the runtime uses (src/game/friendly-scene.ts).',
  'generator':'None. The sheet is a Cycles render of a procedural Blender blockout; no image-generation model was used for this asset.'},
 'source_scripts':{p.name:sha(p) for p in sorted(SOURCE.iterdir()) if p.suffix in ['.py','.mjs','.json','.sh'] and p.is_file()},
 'original_work':['The preserved model-stage source introduced the topology, UVs, weights, 30-joint rig and five clips; this delivery rebuilt and rechecked them; the approved blockout supplied measured proportions, colours, parody hooks and (through its own construction functions) the hood opening, face, mask, eye, fringe, torso, belt, star, coil, cuff, heart and boot coordinates.',
  'Original 1024 painted atlas generated with numpy in Blender Python (paint.py): the grin, teeth, tongue, blush and nose shade on the face, the dew-drop web on the hood (azimuthal crown map), the chest and back webs round the stars (torso front/back regions in the blockout arc-length coordinates), the iris, pupil and glints on the eyes and the finger grooves on the palms, all at the blockout decals\' projected positions; flat sheet-colour tiles for everything else. No external texture.',
  'Mesh, UV, transfer, validation and evidence utilities adapted from the WO111 demon-band-idol / rival-mayor / gadget-helper / golden-after-hours-rat scripts.'],
 'excluded_inputs':['No family photos, names, birthdays or likenesses.','No copied franchise names, models, faces, logos, costumes, lettering, recordings or textures; no spider shape anywhere.'],
 'rights_note':'Original authored study. No exclusive-rights or franchise-endorsement claim.',
 'scope':'Exact candidate, catalog and versioned friendly integration are prepared together. Owner exact-version review, physical-device acceptance and deployment remain separate.'}
settings={**common,
 'blender':{'version':construction['blender_version'],'instance':'blender-authoring (instance 1, primary)','units':'METRIC','unit_scale':1,'authoring_axes':'+Z up / +Y forward (character right = +X)','frames_per_second':30,'animation_mode':'NLA_TRACKS','animation_keys':'Every frame, linear, exported without keyframe optimisation','skin':'One skin; rigid parts plus smoothstep blends at the neck, waist, elbows, hips, knees, ankles, knuckles and fringe (at most 2 influences used)','root':'Identity, fixed floor-centred root; no root animation; the hips carry every translation','bind_pose':'Neutral: head straight, arms in a 45 deg A-pose with a 40 deg elbow bend and open mittens, feet parallel (rest controls reproduce it, max matrix error %.1e)'%construction['rest_reproduction_max_error'],'sheet_pose':'Idle at 0 s reproduces the blockout sheet pose (wrists, ankles, heart buttons and the waving mitten within %.1e m)'%max(construction['sheet_pose_reproduction_m'].values())},
 'export':{'format':'GLB','axes':'+Y up / -Z forward','selection_only':True,'materials':2,'material_notes':'Matte painted atlas for everything except the two heart buttons, which use a second material with the same atlas as an emissive texture at factor 0.35 (the sheet\'s slight heart glow)','texture':{'file':'pigment.png','width':1024,'height':1024,'embedded':True},'no_external_resources':True,'no_required_extensions':True,'compression':'None; no Draco, Meshopt or KTX2 requirement'},
 'preview':{'source':'Exact delivered GLB via Three.js GLTFLoader','three_revision':three['three_revision'],'browser':browser['browser'],'renderer':browser['renderer'],'viewport_px':[800,900],'orthographic_camera':{'left':-0.72,'right':0.72,'top':0.81,'bottom':-0.81,'target':[0,0.60,0],'views':{'front':[0,0.60,-8],'side':[8,0.60,0],'back':[0,0.60,8],'threequarter':[5.657,0.60,-5.657],'beauty':[3.6,2.3,-6.6]}},'stills_pose':'Main stills: idle at 0 s (the sheet pose); rest-*.png: the bind pose','lighting':'Warm hemisphere plus three directional lights; ACES tone mapping exposure 1.0','scales':[1,.35],'no_physical_device_claim':True},
 'checks':{'khronos_zero_errors_warnings':True,'exact_three_and_friendly_runtime_all_checks':True,'chromium_all_clips_normal_small':True,'source_attachment_checks':True}}
visual={**common,
 'author_review':'Exact-export front, side, back and three-quarter stills (idle at 0 s = the sheet pose) compared with the reference sheet at the same angles and metric scale (sheet-vs-export.png); rest-pose stills; the five-clip normal/small motion sheet; attack front/side point-charge-contact-pump and the 35% gameplay-scale strip; held defeat front/side/three-quarter/beauty; close-ups of the face, the waving mitten and cuff, the hip fist, the held-defeat face and the rope-bound boots.',
 'coordinator_review':'Driving Astra reviewed the approved sheet, fresh Blender idle render, exact-export five-clip contact sheet and 35% gameplay-scale strip on September 29 and approved the exact candidate for the private model PR. Tom exact-version review remains pending.','owner_review':'Pending exact-version decision',
 'sheet_matching':['Silhouette kept from the approved blockout at its measured coordinates: idle 0 s measures %.3f m wide x %.4f m tall x %.3f m deep (the blockout: 0.718 x 1.191 x 0.383 m); %.4f m to the crown knot in the bind pose.'%(sp['idle0_dimensions_m'][0],sp['idle0_top_m'],sp['idle0_dimensions_m'][2],three['height_m']),
  'Open-face cobalt hood with the rolled rim, the eight cream dew-drop strands from the crown knot with two sagging rings (painted, clipped 1.17x clear of the face exactly like the blockout) and the six strand-tip drops as small bumps; round face with the tangerine domino mask shell arching over two big friendly eyes (cream whites, warm brown irises, plum pupils, two glints), button nose, big open grin with one rounded strip of top teeth and a pink tongue, pink cheeks and the three chestnut fringe locks.',
  'Cobalt kid suit with the tilted sunny chest star (raised) inside the ten-ray cream web with two scallop rings and dew drops, the smaller back star and web, the tangerine belt with the sunny buckle and the three-loop cream rope coil on its tangerine clip at the right hip.',
  'Sunny mitten gloves with flared cuffs and painted finger grooves, chunky tangerine web-shooter cuffs with the pink heart buttons (softly glowing) and cream nozzles, cobalt leggings and sunny rain boots with rolled cuffs and plum soles.',
  'Idle at 0 s reproduces the sheet pose exactly: the palm-forward wave turned outward with the thumb toward the head, the left fist on the hip above the belt, the head tilted 6 deg into the wave and the toes turned out 8 / 15 deg (wrists within 5e-7 m of the blockout).',
  'Colours are the sheet hex values exactly (atlas); the preview renders them a little deeper than the Cycles Standard-view sheet because of its ACES tone mapping and three-light rig.',
  'Friendly and distinct from the chapter\'s enemies: warm cobalt, sunny yellow and tangerine, the only visible human face in the chapter, open body language, no weapons, blunt rounded teeth, heart buttons as the healer\'s cue; no spider anywhere.'],
 'inherited_source_iteration_notes_rechecked_by_this_delivery':['The first export rendered the lower face cobalt and put the palm grooves off the mitten: the face and mitten projections read their parts\' local (centred) coordinates; both now add the part centre.',
  'The blockout\'s round fringe locks sank 8 mm into the forehead; they are flattened along the face normal (55%) so they sit on it.',
  'The blockout\'s rope coil cut 1-1.4 cm into the right thigh; it now hangs 4.2 cm further out along the belt normal at the same height.',
  'The first held defeat pitched the boots toes-down (a sign error), so the shafts pointed away from the shins; the boots now lie heels-down, toes up, shafts along the shins.',
  'The first rope loop (an ellipse round both boots) grazed each shaft; it is now a racetrack 2.2 cm clear of both parallel shafts, above the boot feet and below the rolled cuffs.',
  'The rope tail first dipped 1 cm below the floor, and while the tangle opened before the feet had settled it dipped 2 cm; the tail is clamped to the floor and the tangle now springs open as he lands.',
  'The first idle wave swung the mitten into the hood; the wave now swings outward from the sheet pose.',
  'The first charge cocked the arm beside the hood and sent the left mitten across the face to tap it; he now charges with the fist in front of his chest and the wind-up and toss detour outward.',
  'The first hit raised the mittens into the hood sides and the first defeat rub pressed the mitten into the hood; both now sit clear, and the flail-to-rub and flail-to-floor moves detour round the hood and the left thigh.',
  'Interpolated 30 fps frames dipped the soles about 1.9 mm; the soles now clear the floor by 3 mm, and the seated pair of boots is lifted together whenever a pitched boot would touch the floor.',
  'The jog first swung the right mitten and forearm into the torso; the jogging wrists sit 3.5 cm further out.'],
 'deviations_from_sheet_notes':['Bind pose is neutral as the notes suggest; the sheet pose is recreated at idle 0 s, so the matched stills show idle 0 s and rest-*.png show the bind pose.',
  'Rig (30 joints): root, hips, spine, chest, neck, head, one fringe bone, a mask bone (the defeat tilt), two eye bones (blink, squeeze and squint by scale), per arm upper arm, forearm, hand, a mitten-finger bone, a thumb bone and a heart-button bone (pulse by scale), per leg thigh, shin and foot, a coil bone and the rope-tangle bone. No clavicles and no toe bones (the rain boots stay rigid on the foot); the spine is hips + spine + chest.',
  'Friendly clip contract: exactly idle, move, attack, hit and defeat. hit is 0.6 s so it completes inside friendly-scene.ts\'s 0.6 s hit window, and hit and attack begin and end exactly on idle 0 s because the runtime switches clips without a fade.',
  'idle has no every-few-loops fist pump (one looping clip cannot vary between loops); it has a blink and two heart pulses per loop instead.',
  'attack follows the notes\' heal toss (spot and point with the hearts blinking, a crouched charge tapping the cuff heart, an overhand toss with the mitten open at a child\'s chest height at the %.2f s contact, a fist pump with a hop), but the charge happens with the fist in front of his chest (beside the hood the arm and the tapping hand crossed the hood), followed by a quick wind-up behind the shoulder. The suggested web-line effect is not implemented; the attack is a studio animation only.'%attack['contact_time_s'],
  'defeat: the coil shrinks to 55%% as it unspools and a cream rope springs round both ankles as he lands (model geometry bound collapsed inside the left boot, opened by the rope bone\'s scale from 0.84 to 0.94 s); he sits with the boots up and bound, the mask tilted %.0f deg, the head tilted %.0f deg, a sheepish squint and the right mitten rubbing the back of his hood; held from %.2f s.'%(dh['mask_roll_deg'],dh['head_turn_deg'],defeat['held_final_pose_from_s']),
  'The coil hangs 4.2 cm further out than the blockout and the soles sit 3 mm above the floor (both for clearance, above).',
  'The heart buttons use a second material with the atlas as a 0.35 emissive texture for the sheet\'s slight glow.'],
 'dimensions_width_height_depth_m':three['dimensions_m'],'rest_bounds_y_up':three['rest_bounds_y_up'],'idle0_sheet_pose_bounds_y_up':sp['idle0_bounds_y_up'],'animated_bounds_y_up':three['all_animation_bounds_y_up'],'stored_safe_culling_bounds':three['exported_safe_bounds_y_up'],
 'sheet_pose_height_m':sp['idle0_top_m'],'contact_seconds':attack['contact_time_s'],'attack_duration_seconds':attack['duration_s'],'hit_duration_seconds':hit['duration_s'],'defeat_held_from_seconds':defeat['held_final_pose_from_s'],
 'defeat_held':dh,'friendly_runtime':rt,'no_floor_penetration':three['checks']['no_floor_penetration'],
 'limitations':['Headless software Chromium is not physical Safari or hardware performance acceptance.',
  'FriendlyScene now registers web-slinger-helper v001 at its measured height. The Three inspection drives the exact asset URL and verifies idle, hit, held defeat, reload and amends through SceneAssets.',
  'The runtime switches clips with stop() and reset().play() and no fade, so a hit that interrupts idle can pop by up to %.2f m (the wave); hit and attack end exactly on idle 0 s, so the return is seamless (%.3f m on the switch frame is ordinary motion).'%(three['continuity']['idle_max_deviation_from_idle0_m'],rt['hit_to_idle_switch_frame_jump_m']),
  'The final export carries a fresh whole-animation envelope. SceneAssets applies it to both primitives; the Three runtime harness asserts this. The isolated preview disables skinned-mesh frustum culling while inspecting every pose.',
  'The attachment audit tests listed part pairs every frame on the source scene; it is not a universal triangle-collision proof. Intended contacts (the fist on the hip, the charging tap on the cuff heart, sleeve roots in the shoulders, legging tops in the torso and seat, the hood round the neck, legging hems in the boots) are not tested, and the rope passes through the boots during the two or three frames in which it springs open (recorded under rope_growth_*).',
  'The painted face cannot change expression; the grin holds in every clip and only the eyes squash (blink, squeeze, squint) and the mask tilts.','Tom exact-version art review and physical-device acceptance remain pending; the family release may use this private candidate under PRD-004 Q-03.']}
bounds={**common,'method':three['method'],'rest_bounds_y_up':three['rest_bounds_y_up'],'dimensions_width_height_depth_m':three['dimensions_m'],'height_m':three['height_m'],'sheet_pose_height_m':sp['idle0_top_m'],'sheet_pose_bounds_y_up':sp['idle0_bounds_y_up'],'sheet_pose_dimensions_m':sp['idle0_dimensions_m'],'sole_clearance_m':three['sole_clearance_m'],'body_footprint_y_up':three['body_footprint_y_up'],'all_animation_bounds_y_up':three['all_animation_bounds_y_up'],'safe_culling_envelope_y_up':three['exported_safe_bounds_y_up'],'defeat_held_hips_height_m':dh['hips_height_m'],'note':'glTF axes: +Y up, character faces -Z; his right hand (the wave) is +X. Root at the floor origin under the body centre. The bind pose holds the arms out in an A-pose (hence the %.2f m rest width); the sheet pose is %.3f m wide (the blockout measured 0.718 m).'%(three['dimensions_m'][0],sp['idle0_dimensions_m'][0])}
for name,record in [('provenance.json',provenance),('tool-settings.json',settings),('visual-review.json',visual),('bounds.json',bounds)]:
 (ROOT/name).write_text(json.dumps(record,indent=2)+'\n')
print(json.dumps({'glb_sha256':digest,'reports':['provenance.json','tool-settings.json','visual-review.json','bounds.json'],'all_technical_checks':True}))
