/**
 * World B, chapter 3: Besties' Big Stage (`family-b3-stage`), generated by
 * `scripts/levels/family/b3.ts` (PLAN-019 blueprint B3, the critique's B3
 * items and coordinator rulings R1–R14).
 *
 * Every claim here runs the real validators, the family-world lints and the
 * real `stepObby` through the growth and kid-model auto-pilots. The avatar
 * uses only the moves unlocked at the chapter's start age of 4 (jump, high
 * jump, double jump). No real names, dates or photos: the worlds below use
 * the fictional World B birth date and synthetic filler chapters.
 */
import { describe, expect, it } from "vitest";
import {
  abilitiesForAge,
  GROWTH_MOVE_IDS,
  type AbilitySet,
  type RequirableGrowthMove,
} from "../../src/shared/abilities";
import {
  AUTHORED_LEVEL_V4_LIMITS,
  isAuthoredSurfacePiece,
  resolveAuthoredLevelDocument,
  validateAuthoredLevelDocument,
  type AuthoredConnection,
  type AuthoredSurfacePiece,
} from "../../src/shared/authored-level";
import { validateGrowthRequirements } from "../../src/shared/authored-level-growth";
import { validateEditorGameplayGuards } from "../../src/shared/editor-gameplay-guards";
import {
  applyLevelEditorCommands,
  createWorldEditorProject,
  validateLevelEditorProject,
  type LevelEditorCommand,
} from "../../src/shared/editor-project";
import {
  bossRetryRoute,
  connectionStrips,
  lintFamilyChapter,
} from "../../src/shared/family-world-lint";
import {
  decorWorldBounds,
  placeableThemeKitProps,
  themeKitProp,
} from "../../src/shared/theme-kits";
import { planCasinoCollectibles } from "../../src/game/casino-tokens";
import { enemyAttackRange } from "../../src/game/combat";
import {
  chapterCommands,
  worldShellCommands,
  type WorldShellChapter,
} from "../../scripts/levels/lib/growth-kit";
import {
  FAMILY_B3_BOSS,
  FAMILY_B3_BRANCHES,
  FAMILY_B3_COPY,
  FAMILY_B3_HEIGHTS,
  FAMILY_B3_MAIN_PATH,
  FAMILY_B3_ORDINARY,
  FAMILY_B3_ROUTE_ID,
  familyB3Level,
} from "../../scripts/levels/family/b3";
import {
  inputToward,
  sampledPlatform,
  STAGES,
} from "../game/authored-traversal-lib";
import {
  createGrowthSimulation,
  growthStep,
  missGrowthPractice,
  traverseGrowthEdge,
} from "../game/growth-traversal-lib";
import {
  bounceWalkOn,
  liftWalkIn,
  R2_STICKS,
  runGrowthRouteWithWaits,
} from "../game/family-kid-lib";

const document = familyB3Level();
const level = resolveAuthoredLevelDocument(document);
const startAge = 4;
const startAbilities = abilitiesForAge(startAge);
const H = FAMILY_B3_HEIGHTS;

/** The smallest ladder prefix that includes `move`: a branch's declared move and nothing later. */
function abilitiesThrough(move: RequirableGrowthMove): AbilitySet {
  return GROWTH_MOVE_IDS.slice(0, GROWTH_MOVE_IDS.indexOf(move) + 1);
}

function step(path: readonly string[], connection: AuthoredConnection): boolean {
  const index = path.indexOf(connection.from);
  return index >= 0 && path[index + 1] === connection.to;
}

const mainEdges = document.connections.filter((connection) =>
  step(document.mainPath, connection),
);
const branchEdges = document.connections.filter((connection) =>
  document.branches.some((branch) => step(branch, connection)),
);
const pathEdges = new Set([...mainEdges, ...branchEdges]);
const offPathEdges = document.connections.filter((connection) => !pathEdges.has(connection));
const label = (connection: AuthoredConnection) => `${connection.from}->${connection.to}`;

const surfaces = new Map(
  document.pieces
    .filter(isAuthoredSurfacePiece)
    .map((piece): [string, AuthoredSurfacePiece] => [piece.id, piece]),
);
const topOf = (id: string): number => {
  const surface = surfaces.get(id)!;
  return surface.center.y + surface.size.y / 2;
};

// ---------------------------------------------------------------------------
// Worlds for (a). The World B template's fictional birth date (WORLD-SPEC).
// ---------------------------------------------------------------------------

const BIRTH = "2020-06-01";

function shellChapter(
  chapterId: string,
  routeId: string,
  theme: WorldShellChapter["theme"],
  fromYears: number,
  toYears: number,
  labels: readonly [string, string, string],
): WorldShellChapter {
  const year = Number(BIRTH.slice(0, 4));
  const on = (years: number, monthDay = BIRTH.slice(5)) => `${year + years}-${monthDay}`;
  return {
    chapterId,
    routeId,
    name: chapterId === "family-b3" ? FAMILY_B3_COPY.name : `Synthetic ${chapterId}`,
    subtitle: chapterId === "family-b3" ? FAMILY_B3_COPY.subtitle : "A synthetic filler chapter",
    description:
      chapterId === "family-b3"
        ? FAMILY_B3_COPY.description
        : "A synthetic chapter that only sets the ages before chapter three.",
    theme,
    representedDateRange: { startDate: on(fromYears), endDate: on(toYears) },
    recoveredAge: { fromYears, toYears },
    previewMemories: [
      { slotId: "minor-one", date: on(fromYears, "12-15"), label: labels[0] },
      { slotId: "minor-two", date: on(fromYears + 1, "03-15"), label: labels[1] },
      { slotId: "major", date: on(toYears), label: labels[2] },
    ],
  };
}

const B3_CHAPTER = shellChapter("family-b3", FAMILY_B3_ROUTE_ID, FAMILY_B3_COPY.theme, 4, 6, [
  "Front-row seats",
  "Dance party",
  "Turning 6!",
]);

/** The chapter's level and cast: one ordinary identity in all four slots, the catalog Besties boss. */
function b3Commands(): LevelEditorCommand[] {
  const b3 = chapterCommands(B3_CHAPTER.chapterId);
  const idol = { source: "candidate" as const, candidateId: FAMILY_B3_ORDINARY.id };
  return [
    b3.replaceLevel(familyB3Level()),
    b3.addCandidate("ordinary-1", FAMILY_B3_ORDINARY),
    b3.assign("ordinary-2", idol),
    b3.assign("ordinary-3", idol),
    b3.assign("ordinary-4", idol),
    b3.assign("boss", FAMILY_B3_BOSS),
  ];
}

function buildWorld(projectId: string, chapters: readonly WorldShellChapter[]) {
  const result = applyLevelEditorCommands(
    createWorldEditorProject({ projectId, catalogVersion: "parody-catalog-v7" }),
    {
      expectedRevision: 0,
      commands: [
        ...worldShellCommands({ fictionalBirthDate: BIRTH, chapters }),
        ...b3Commands(),
      ],
    },
  );
  expect(result.ok).toBe(true);
  return result.project;
}

describe("Besties' Big Stage (World B chapter 3, family-b3-stage)", () => {
  it("is a pure, deterministic authored-level-v4 document", () => {
    expect(familyB3Level()).toEqual(document);
    expect(JSON.stringify(familyB3Level())).toBe(JSON.stringify(document));
    expect(document).toMatchObject({
      schemaVersion: "authored-level-v4",
      id: FAMILY_B3_ROUTE_ID,
      theme: "party",
    });
    expect(document.mainPath).toEqual(FAMILY_B3_MAIN_PATH);
    expect(document.branches).toEqual(FAMILY_B3_BRANCHES);
  });

  describe("(a) validation", () => {
    it("has no issues inside a World B shaped world, with its cast and the Besties court guard", () => {
      // Two synthetic garden chapters (0→2, 2→4) put chapter three at its real
      // start age with the real previous start age, as World B will.
      const project = buildWorld("family-b3-world", [
        shellChapter("filler-b1", "filler-b1-route", "playroom", 0, 2, [
          "Summer picnic",
          "A sunny afternoon",
          "Turning 2!",
        ]),
        shellChapter("filler-b2", "filler-b2-route", "casita", 2, 4, [
          "Garden games",
          "Splash day",
          "Turning 4!",
        ]),
        B3_CHAPTER,
      ]);
      expect(validateLevelEditorProject(project)).toEqual([]);
      const chapter = project.chapters.at(-1)!;
      expect(chapter.level).toEqual(document);
      expect("encounterSlots" in chapter && chapter.encounterSlots.boss).toEqual(FAMILY_B3_BOSS);
    });

    it("as a world's only chapter, reports only that a first chapter must start on the birth date", () => {
      // A one-chapter world cannot hold a 4→6 chapter: the world shell makes
      // the first chapter start on the fictional birth date. Everything else,
      // the level, cast, dates and ages, validates.
      const project = buildWorld("family-b3-alone", [B3_CHAPTER]);
      expect(validateLevelEditorProject(project).map((entry) => [entry.path, entry.code])).toEqual([
        ["$.chapters[0].representedDateRange.startDate", "date.birth-start"],
      ]);
    });

    it("passes the level validator, the strictest growth context and the Besties court guard on its own", () => {
      expect(validateAuthoredLevelDocument(document)).toEqual([]);
      // No previous chapter: high jump and double jump both count as new, so
      // this also proves no required high jump needs a practice stretch.
      expect(validateGrowthRequirements(document, { startAgeYears: startAge })).toEqual([]);
      expect(
        validateGrowthRequirements(document, {
          startAgeYears: startAge,
          previousStartAgeYears: 2,
        }),
      ).toEqual([]);
      expect(validateEditorGameplayGuards(document, { hostsBestiesRoutine: true })).toEqual([]);
    });
  });

  it("(b) has no family-world lint findings with the World B preset", () => {
    // No errors, and no warnings either (a lift step-up would be one).
    expect(lintFamilyChapter(document, { world: "b" })).toEqual([]);
  });

  describe("(c) pacing (R10)", () => {
    it.each(STAGES)(
      "a %s avatar with start-age moves crosses the whole required route without a recovery in at least 70 s",
      (stage) => {
        const run = runGrowthRouteWithWaits(level, document.mainPath, stage, startAbilities);
        expect(run.failedAt).toBeNull();
        expect(run.recoveries).toBe(0);
        expect(run.completed).toHaveLength(document.mainPath.length - 1);
        expect(run.bounces).toEqual(["encore-trampoline", "confetti-cannon"]);
        expect(run.seconds).toBeGreaterThanOrEqual(70);
        // The stage lift (12 s cycle) quantizes the run: the child reaches its
        // dock about 56 s in, inside the 50–62 s window that boards at the
        // 60 s bottom stop, so small timing changes keep this total.
        expect(run.seconds).toBeCloseTo(74.33, 1);
      },
    );
  });

  describe("(d) kid model: bounce pads (R2) and the stage lift (R6)", () => {
    const bounces = mainEdges.filter((connection) => connection.mode === "bounce");
    const lifts = mainEdges.filter(
      (connection) => connection.mode === "ride" && surfaces.get(connection.to)?.type === "lift",
    );

    it("has two required bounces and one required lift", () => {
      expect(bounces.map(label)).toEqual([
        "encore-trampoline->fan-balcony",
        "confetti-cannon->sky-bleachers",
      ]);
      expect(lifts.map(label)).toEqual(["lift-dock->stage-lift"]);
    });

    describe.each(STAGES)("%s avatar", (stage) => {
      it.each(bounces.map((connection) => [label(connection), connection] as const))(
        "walks onto %s at every R2 stick from the middle and both sides, without pressing Jump",
        (_label, connection) => {
          const approach = document.connections.find(
            (candidate) => candidate.to === connection.from && candidate.mode === "walk",
          )!;
          for (const lateral of [0, -1.2, 1.2])
            for (const stick of R2_STICKS) {
              const result = bounceWalkOn(level, approach.from, connection.from, connection.to, {
                stick,
                stage,
                lateral,
              });
              expect(result.startedOnSource, `stick ${stick}, lateral ${lateral}`).toBe(true);
              expect(result.reached, `stick ${stick}, lateral ${lateral}`).toBe(true);
              expect(result.recovered).toBe(false);
            }
        },
      );

      it.each(lifts.map((connection) => [label(connection), connection] as const))(
        "rides %s or falls into the open shaft, never stuck, whenever a child walks in",
        (_label, connection) => {
          const exit = document.connections.find(
            (candidate) => candidate.from === connection.to && candidate.mode === "ride",
          )!;
          for (const stick of [1, 0.6, 0.4]) {
            const result = liftWalkIn(level, connection.to, connection.from, exit.to, {
              phases: 24,
              stage,
              stick,
            });
            // Dwell does not close the shaft (DESIGN-025 D-08 (f)); the
            // boarding checkpoint below turns each fall into a short retry.
            expect(result.other, `stick ${stick}`).toBe(0);
            expect(result.ok + result.fell).toBe(24);
            expect(result.ok, `stick ${stick}`).toBeGreaterThanOrEqual(8);
          }
        },
      );

      it("respawns a child who walks into the empty shaft on the lift dock's checkpoint", () => {
        const dock = surfaces.get("lift-dock")!;
        const lift = level.course.platforms.find((platform) => platform.id === "stage-lift")!;
        const simulation = createGrowthSimulation(level, stage, startAbilities, {
          x: dock.center.x,
          y: topOf("lift-dock"),
          z: dock.center.z,
        });
        growthStep(simulation, { move: { moveX: 0, moveY: 0 } });
        expect(simulation.state.checkpointId).toBe("lift-dock-safe");
        // Wait until the lift has left for the wing, then walk straight in.
        const liftTop = () => {
          const sampled = sampledPlatform(level.course, "stage-lift", simulation.timeSeconds);
          return sampled.center.y + sampled.size.y / 2;
        };
        while (liftTop() < topOf("lift-dock") + 1)
          growthStep(simulation, { move: { moveX: 0, moveY: 0 } });
        const walkedIn = simulation.timeSeconds;
        for (let frame = 0; frame < 300 && simulation.recoveries === 0; frame += 1)
          growthStep(simulation, { move: inputToward(simulation.state, lift.center) });
        expect(simulation.recoveries).toBe(1);
        growthStep(simulation, { move: { moveX: 0, moveY: 0 } });
        expect(simulation.state.grounded).toBe(true);
        expect(simulation.state.supportId).toBe("lift-dock");
        expect(simulation.state.checkpointId).toBe("lift-dock-safe");
        // Walk in, fall and stand back on the dock within a few seconds.
        expect(simulation.timeSeconds - walkedIn).toBeLessThan(4);
      });
    });
  });

  describe("(e) every edge with its declared move", () => {
    describe.each(STAGES)("%s avatar", (stage) => {
      it.each(mainEdges.map((connection) => [label(connection), connection] as const))(
        "crosses required edge %s with start-age moves at three lateral offsets",
        (_label, connection) => {
          for (const lateral of [0, -0.6, 0.6]) {
            const result = traverseGrowthEdge(level, connection, stage, startAbilities, lateral);
            expect(result.startedOnSource, `lateral ${lateral}`).toBe(true);
            expect(result.recovered, `lateral ${lateral}`).toBe(false);
            expect(result.reached, `lateral ${lateral}`).toBe(true);
          }
        },
      );

      it.each(branchEdges.map((connection) => [label(connection), connection] as const))(
        "crosses branch edge %s with its declared move",
        (_label, connection) => {
          const abilities = connection.requires
            ? abilitiesThrough(connection.requires)
            : startAbilities;
          const result = traverseGrowthEdge(level, connection, stage, abilities);
          expect(result.startedOnSource).toBe(true);
          expect(result.recovered).toBe(false);
          expect(result.reached).toBe(true);
        },
      );

      it.each(offPathEdges.map((connection) => [label(connection), connection] as const))(
        "crosses practice-floor edge %s",
        (_label, connection) => {
          const result = traverseGrowthEdge(level, connection, stage, startAbilities);
          expect(result.startedOnSource).toBe(true);
          expect(result.reached).toBe(true);
        },
      );

      it.each(
        mainEdges
          .filter((connection) => connection.safeMissPlatformId)
          .map((connection) => [label(connection), connection] as const),
      )("misses practice jump %s onto the soft floor", (_label, connection) => {
        const result = missGrowthPractice(level, connection, stage, startAbilities);
        expect(result.startedOnSource).toBe(true);
        expect(result.airborne).toBe(true);
        expect(result.recovered).toBe(false);
        expect(result.reached).toBe(true);
        expect(result.supportId).toBe("soft-practice-floor");
      });
    });

    it("asks for the double jump only on the two practice rungs, which high jump alone cannot reach", () => {
      const required = mainEdges.filter((connection) => connection.requires);
      expect(required.map((connection) => [label(connection), connection.requires])).toEqual([
        ["fan-walk->spotlight-riser", "double-jump"],
        ["spotlight-riser->rehearsal-loft", "double-jump"],
      ]);
      for (const connection of required) {
        expect(connection.safeMissPlatformId).toBe("soft-practice-floor");
        for (const stage of STAGES)
          expect(traverseGrowthEdge(level, connection, stage, abilitiesForAge(2)).reached).toBe(false);
      }
      // The catch floor spans both rungs, 16 m wide.
      expect(surfaces.get("soft-practice-floor")!.size.x).toBeGreaterThanOrEqual(16);
    });
  });

  describe("(f) the climb", () => {
    it("rises through four bands to the 11.3 m main stage, the grandest World B chapter (R8)", () => {
      expect(document.mainPath.map((id) => [id, Number(topOf(id).toFixed(3))])).toEqual([
        ["stage-door-plaza", H.plaza],
        ["fan-walk", H.plaza],
        ["spotlight-riser", H.riser],
        ["rehearsal-loft", H.loft],
        ["fan-picnic", H.picnic],
        ["ribbon-runway", H.picnic],
        ["ribbon-bandstand", H.bandstand],
        ["relay-hop-1", H.bandstand],
        ["relay-hop-2", H.bandstand],
        ["bounce-deck", H.bandstand],
        ["encore-trampoline", H.bandstand],
        ["fan-balcony", H.balcony],
        ["speaker-raft", H.balcony],
        ["raft-dock", H.balcony],
        ["amp-hop-1", H.hops],
        ["amp-hop-2", H.hops],
        ["glitter-grove", H.hops],
        ["turnstile-deck", H.hops],
        ["merch-fair", H.hops],
        ["cannon-deck", H.hops],
        ["confetti-cannon", H.hops],
        ["sky-bleachers", H.sky],
        ["sky-catwalk", H.sky],
        ["glow-hop-1", H.sky],
        ["glow-hop-2", H.sky],
        ["glow-hop-3", H.sky],
        ["crowd-bridge", H.sky],
        ["lift-dock", H.sky],
        // The lift's bottom stop sits 0.1 m under its dock.
        ["stage-lift", H.liftBottom],
        ["stage-wing", H.wing],
        ["stage-stair-1", H.stair1],
        ["stage-stair-2", H.stair2],
        ["main-stage", H.stage],
        ["encore-riser", H.stage],
      ]);
      const tops = document.mainPath.map(topOf);
      // Never more than a plain jump down, and it only ever climbs overall.
      for (let index = 1; index < tops.length; index += 1)
        expect(tops[index]! - tops[index - 1]!).toBeGreaterThanOrEqual(-0.1 - 1e-9);
      expect(Math.max(...tops)).toBe(H.stage);
      expect(H.stage).toBeGreaterThanOrEqual(10);
      expect(H.stage - H.plaza).toBeGreaterThanOrEqual(10);
      // L0 (≤0.3), L1 (2.7–3.3), L2 (5.3–6.8) and L3 (10.4–11.3).
      const bands = [
        [0, 0.3],
        [2.7, 3.3],
        [5.3, 6.8],
        [10.4, 11.3],
      ] as const;
      for (const [low, high] of bands)
        expect(tops.some((top) => top >= low - 1e-9 && top <= high + 1e-9)).toBe(true);
      // The big vertical moments: rungs +2.4 m, trampoline +2.0, cannon +1.2, lift +3.8.
      expect(topOf("fan-balcony") - topOf("encore-trampoline")).toBeCloseTo(2, 6);
      expect(topOf("sky-bleachers") - topOf("confetti-cannon")).toBeCloseTo(1.2, 6);
      expect(H.liftTop - H.liftBottom).toBeCloseTo(3.8, 6);
      const run = runGrowthRouteWithWaits(level, document.mainPath, "child", startAbilities);
      expect(run.maxFeetY).toBeGreaterThanOrEqual(H.stage);
    });
  });

  describe("chapter rulings", () => {
    it("opens on the fan walk (R9) and reaches the boss by the rising stage lift", () => {
      expect(mainEdges[0]).toEqual({ from: "stage-door-plaza", to: "fan-walk", mode: "walk" });
      expect(surfaces.get("fan-walk")!.size.z).toBeGreaterThanOrEqual(20);
      const lift = document.pieces.find((piece) => piece.type === "lift")!;
      expect(document.pieces.filter((piece) => piece.type === "lift")).toHaveLength(1);
      expect(lift.type === "lift" && lift.travel).toEqual({ distance: 3.8, period: 8, dwell: 2 });
      expect(document.mainPath.indexOf("stage-lift")).toBeLessThan(
        document.mainPath.indexOf("main-stage"),
      );
    });

    it("keeps boss retries short and each minor memory ahead of the fights it covers (R5)", () => {
      const { memories, encounters } = document.anchors;
      expect(memories["minor-two"].platformId).toBe("stage-wing");
      expect(bossRetryRoute(document)).toEqual({ meters: expect.any(Number), lifts: 0 });
      expect(bossRetryRoute(document)!.meters).toBeLessThanOrEqual(25);
      // An HP defeat returns to the furthest minor memory: fights 3 and 4
      // both follow minor one closely, the way bossRetryRoute measures it.
      const index = (id: string) => document.mainPath.indexOf(id);
      const minorOne = memories["minor-one"];
      expect(index(minorOne.platformId)).toBeGreaterThan(index(encounters["ordinary-2"].platformId));
      const retryMeters = (slot: "ordinary-3" | "ordinary-4") => {
        const { platformId, arena, position } = encounters[slot];
        let previous = minorOne.position;
        let meters = 0;
        for (const id of document.mainPath.slice(index(minorOne.platformId) + 1, index(platformId))) {
          const point = { x: surfaces.get(id)!.center.x, y: topOf(id), z: surfaces.get(id)!.center.z };
          meters += Math.hypot(point.x - previous.x, point.y - previous.y, point.z - previous.z);
          previous = point;
        }
        const nearest = {
          x: Math.max(arena.minX, Math.min(arena.maxX, previous.x)),
          z: Math.max(arena.minZ, Math.min(arena.maxZ, previous.z)),
        };
        return meters + Math.hypot(nearest.x - previous.x, position.y - previous.y, nearest.z - previous.z);
      };
      expect(index(minorOne.platformId)).toBeLessThanOrEqual(index(encounters["ordinary-3"].platformId));
      expect(minorOne.position.x).toBeLessThan(encounters["ordinary-3"].arena.minX);
      expect(retryMeters("ordinary-3")).toBeLessThanOrEqual(5);
      expect(retryMeters("ordinary-4")).toBeLessThanOrEqual(30);
      // Each minor memory's deck holds exactly one checkpoint.
      for (const slot of ["minor-one", "minor-two"] as const)
        expect(
          document.pieces.filter(
            (piece) => piece.type === "checkpoint" && piece.platformId === memories[slot].platformId,
          ),
        ).toHaveLength(1);
    });

    it("uses one ordinary identity in all four slots (R11)", () => {
      const { encounters } = document.anchors;
      expect(
        (["ordinary-1", "ordinary-2", "ordinary-3", "ordinary-4"] as const).map(
          (slot) => encounters[slot].kind,
        ),
      ).toEqual(["ordinary-a", "ordinary-a", "ordinary-a", "ordinary-a"]);
      expect(FAMILY_B3_ORDINARY).toMatchObject({ kind: "ordinary-a", periodId: FAMILY_B3_COPY.periodId });
    });

    it("keeps every friendly's healing circle outside every ordinary's reach", () => {
      const reach = 1.7 + enemyAttackRange("ordinary");
      for (const friendly of Object.values(document.anchors.friendlies))
        for (const slot of ["ordinary-1", "ordinary-2", "ordinary-3", "ordinary-4"] as const) {
          const { arena } = document.anchors.encounters[slot];
          const nearest = {
            x: Math.max(arena.minX, Math.min(arena.maxX, friendly.position.x)),
            z: Math.max(arena.minZ, Math.min(arena.maxZ, friendly.position.z)),
          };
          expect(
            Math.hypot(friendly.position.x - nearest.x, friendly.position.z - nearest.z),
          ).toBeGreaterThan(reach);
        }
    });

    it("lists its checkpoints in route order", () => {
      const order = [...document.mainPath];
      const checkpoints = document.pieces.flatMap((piece) =>
        piece.type === "checkpoint" ? [order.indexOf(piece.platformId)] : [],
      );
      expect(checkpoints.every((index) => index >= 0)).toBe(true);
      expect(checkpoints).toEqual([...checkpoints].sort((left, right) => left - right));
    });

    it("hides a golden ticket on each optional route, the lighting rig first (R10)", () => {
      const plan = planCasinoCollectibles({ authored: document, course: level.course })!;
      expect(plan.tickets.map((ticket) => ticket.platformId)).toEqual([
        "golden-perch",
        "friend-balcony",
        "confetti-crate",
      ]);
      expect(plan.tokens.length).toBeGreaterThan(40);
    });

    it("dresses the chapter only with party-kit props, beside every lane (R12)", () => {
      const decor = document.decor ?? [];
      expect(decor.length).toBeGreaterThanOrEqual(50);
      expect(decor.length).toBeLessThanOrEqual(AUTHORED_LEVEL_V4_LIMITS.maxDecor);
      const allowed = new Set(placeableThemeKitProps("party").map((prop) => prop.id));
      const strips = document.connections.flatMap((connection) =>
        connectionStrips(surfaces.get(connection.from)!, surfaces.get(connection.to)!),
      );
      const footprints = [...surfaces.values()].map((surface) => ({
        minX: surface.center.x - surface.size.x / 2,
        maxX: surface.center.x + surface.size.x / 2,
        minZ: surface.center.z - surface.size.z / 2,
        maxZ: surface.center.z + surface.size.z / 2,
      }));
      const boxes = decor.map((entry) => {
        expect(entry.id).toMatch(/^[a-z][a-z0-9-]*$/);
        expect(allowed.has(entry.kitPropId), entry.kitPropId).toBe(true);
        const prop = themeKitProp(entry.kitPropId)!;
        // Party kit only: no shared GLB enters gameplay from this chapter.
        expect(prop.theme).toBe("party");
        const bounds = decorWorldBounds(prop.bounds, entry);
        return { id: entry.id, bounds };
      });
      for (const { id, bounds } of boxes) {
        const rect = { minX: bounds.min.x, maxX: bounds.max.x, minZ: bounds.min.z, maxZ: bounds.max.z };
        const overlaps = (other: typeof rect) =>
          Math.min(rect.maxX, other.maxX) - Math.max(rect.minX, other.minX) > 1e-6 &&
          Math.min(rect.maxZ, other.maxZ) - Math.max(rect.minZ, other.minZ) > 1e-6;
        // Every prop stands on the ground plane beside the course: no footprint
        // under or over a deck, a jump strip or a lift or pad approach, at any
        // height, so no arch straddles a lane.
        expect(bounds.min.y, id).toBeCloseTo(-1.4, 6);
        expect(footprints.some(overlaps), id).toBe(false);
        expect(strips.some(overlaps), id).toBe(false);
        // Nothing behind the spawn, where the follow camera sits.
        expect(rect.maxZ, id).toBeLessThan(document.anchors.spawn.position.z + 1.5);
      }
      for (let first = 0; first < boxes.length; first += 1)
        for (let second = first + 1; second < boxes.length; second += 1) {
          const a = boxes[first]!.bounds;
          const b = boxes[second]!.bounds;
          const apart =
            Math.min(a.max.x, b.max.x) - Math.max(a.min.x, b.min.x) <= 1e-6 ||
            Math.min(a.max.z, b.max.z) - Math.max(a.min.z, b.min.z) <= 1e-6;
          expect(apart, `${boxes[first]!.id} / ${boxes[second]!.id}`).toBe(true);
        }
    });
  });
});
