/**
 * The checked-in family world templates (DESIGN-024 overview, WO109), kept
 * apart from the registry so save validation can resolve a frozen plan's
 * template without importing the setup service.
 */
import ratCasinoWorldV1 from '../../shared/levels/rat-casino-world-v1.json';
import ratCasinoWorldV2 from '../../shared/levels/rat-casino-world-v2.json';
import familyWorldAV1 from '../../shared/levels/family-world-a-v1.json';
import familyWorldAV2 from '../../shared/levels/family-world-a-v2.json';
import familyWorldAV3 from '../../shared/levels/family-world-a-v3.json';
import familyWorldAV4 from '../../shared/levels/family-world-a-v4.json';
import familyWorldAV5 from '../../shared/levels/family-world-a-v5.json';
import familyWorldAV7 from '../../shared/levels/family-world-a-v7.json';
import familyWorldAV8 from '../../shared/levels/family-world-a-v8.json';
import familyWorldAV9 from '../../shared/levels/family-world-a-v9.json';
import type { FriendlyCatalogVersion } from '../../shared/friendly.js';
import familyWorldBV1 from '../../shared/levels/family-world-b-v1.json';
import familyWorldBV2 from '../../shared/levels/family-world-b-v2.json';
import familyWorldBV3 from '../../shared/levels/family-world-b-v3.json';
import familyWorldBV4 from '../../shared/levels/family-world-b-v4.json';
import familyWorldBV5 from '../../shared/levels/family-world-b-v5.json';
import familyWorldBV6 from '../../shared/levels/family-world-b-v6.json';
import familyWorldBV7 from '../../shared/levels/family-world-b-v7.json';
import familyWorldBV8 from '../../shared/levels/family-world-b-v8.json';

export interface FamilyTemplateSource {
  readonly id: string;
  readonly version: string;
  readonly project: unknown;
  readonly friendlyCatalogVersion?: FriendlyCatalogVersion;
}

/**
 * The checked-in registry. Each family world is generated by
 * `scripts/levels/build-family-world-<key>.ts`; its project name is the name
 * administrators see (World A: "Clubhouse to Casino"; World B: "Playroom to
 * Big Stage"). A content fix is a new version beside the old one, never an
 * edit: World A v2 carries the fixes found in verification, and v1 stays for
 * the journeys published on it. The v3 of each world is its v2 levels with the
 * landed family-era models cast from parody-catalog-v10; v1 and v2 stay. The
 * v4 of each world is its v3 plus the DESIGN-027 scare levels (A3 and B3
 * spooky, A4 scary); v1 to v3 stay.
 */
export const CHECKED_IN_FAMILY_TEMPLATES: readonly FamilyTemplateSource[] = Object.freeze([
  { id: 'rat-casino-world', version: 'v1', project: ratCasinoWorldV1 },
  { id: 'rat-casino-world', version: 'v2', project: ratCasinoWorldV2 },
  // v1 stays registered: journeys already published on it keep loading.
  { id: 'family-world-a', version: 'v1', project: familyWorldAV1 },
  { id: 'family-world-a', version: 'v2', project: familyWorldAV2 },
  { id: 'family-world-a', version: 'v3', project: familyWorldAV3 },
  { id: 'family-world-a', version: 'v4', project: familyWorldAV4 },
  { id: 'family-world-a', version: 'v5', project: familyWorldAV5 },
  { id: 'family-world-a', version: 'v6', project: familyWorldAV5, friendlyCatalogVersion: 'friendly-catalog-v2' },
  { id: 'family-world-a', version: 'v7', project: familyWorldAV7, friendlyCatalogVersion: 'friendly-catalog-v2' },
  { id: 'family-world-a', version: 'v8', project: familyWorldAV8, friendlyCatalogVersion: 'friendly-catalog-v2' },
  { id: 'family-world-a', version: 'v9', project: familyWorldAV9, friendlyCatalogVersion: 'friendly-catalog-v2' },
  { id: 'family-world-b', version: 'v1', project: familyWorldBV1 },
  { id: 'family-world-b', version: 'v2', project: familyWorldBV2 },
  { id: 'family-world-b', version: 'v3', project: familyWorldBV3 },
  { id: 'family-world-b', version: 'v4', project: familyWorldBV4 },
  { id: 'family-world-b', version: 'v5', project: familyWorldBV5 },
  { id: 'family-world-b', version: 'v6', project: familyWorldBV6 },
  { id: 'family-world-b', version: 'v7', project: familyWorldBV7 },
  { id: 'family-world-b', version: 'v8', project: familyWorldBV8 },
]);
