/**
 * The checked-in family world templates (DESIGN-024 overview, WO109), kept
 * apart from the registry so save validation can resolve a frozen plan's
 * template without importing the setup service.
 */
import ratCasinoWorldV1 from '../../shared/levels/rat-casino-world-v1.json';
import ratCasinoWorldV2 from '../../shared/levels/rat-casino-world-v2.json';
import familyWorldAV1 from '../../shared/levels/family-world-a-v1.json';
import familyWorldAV2 from '../../shared/levels/family-world-a-v2.json';
import familyWorldBV1 from '../../shared/levels/family-world-b-v1.json';
import familyWorldBV2 from '../../shared/levels/family-world-b-v2.json';

export interface FamilyTemplateSource {
  readonly id: string;
  readonly version: string;
  readonly project: unknown;
}

/**
 * The checked-in registry. Each family world is generated by
 * `scripts/levels/build-family-world-<key>.ts`; its project name is the name
 * administrators see (World A: "Clubhouse to Casino"; World B: "Playroom to
 * Big Stage"). A content fix is a new version beside the old one, never an
 * edit: World A v2 carries the fixes found in verification, and v1 stays for
 * the journeys published on it.
 */
export const CHECKED_IN_FAMILY_TEMPLATES: readonly FamilyTemplateSource[] = Object.freeze([
  { id: 'rat-casino-world', version: 'v1', project: ratCasinoWorldV1 },
  { id: 'rat-casino-world', version: 'v2', project: ratCasinoWorldV2 },
  // v1 stays registered: journeys already published on it keep loading.
  { id: 'family-world-a', version: 'v1', project: familyWorldAV1 },
  { id: 'family-world-a', version: 'v2', project: familyWorldAV2 },
  { id: 'family-world-b', version: 'v1', project: familyWorldBV1 },
  { id: 'family-world-b', version: 'v2', project: familyWorldBV2 },
]);
