"""WO111 yes-yes-veggie exact-byte authoring provenance, bounds and factual review handoff."""
from pathlib import Path
import json,hashlib,datetime
ROOT=Path('/home/dev/artifacts/haynes-quest/family-eras/yes-yes-veggie/v001')
SOURCE=Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
digest=sha(ROOT/'yes-yes-veggie.glb')
construction=json.loads((ROOT/'construction.json').read_text())
three=json.loads((ROOT/'three-inspection.json').read_text())
browser=json.loads((ROOT/'final-preview/browser-inspection.json').read_text())
validation=json.loads((ROOT/'validation.json').read_text())
attachments=json.loads((ROOT/'attachment-inspection.json').read_text())
for report in [three,browser,validation,attachments]:
 assert report.get('glb_sha256',report.get('sha256'))==digest
 assert all(report['checks'].values()),report['checks']
assert construction['files']['yes-yes-veggie.glb']['sha256']==digest
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
common={'work_order':'WO111','asset_id':'yes-yes-veggie','version':'v001','created_utc':now,'glb_sha256':digest,'candidate_status':"Awaiting Tom's review · used in the family release"}
contact=next(c for c in construction['clips'] if c['name']=='attack')
defeat=next(c for c in construction['clips'] if c['name']=='defeat')
provenance={**common,
 'authoring_agent':'Claude Opus 5.5 (claude-opus-5-5, xhigh) Blender author under the PLAN-019 coordinator; Tom ruled on Sept 26 that Opus 5.5 continues WO111 Blender work after the Codex usage limit (WO111 update on origin/main). This continuation took over the scene lease of an earlier Opus 5.5 run of the same work order that stopped after a static checkpoint without releasing.',
 'authoring_tool':'Blender MCP execute_blender_code on the dedicated authoring service','blender_version':construction['blender_version'],
 'source_concept':{'file':'concept.png','sha256':sha(ROOT/'concept.png'),'source_record':'source.json','earlier_draft':'concept-draft.png','generator':'OpenAI built-in image_gen tool, driving GPT-6 Astra / max','selection':'Driving Astra selected the framing-revised original concept before the Codex usage limit; no franchise source media. Not a Blender reference sheet.'},
 'preserved_checkpoints':{'checkpoint1':{'glb':'yes-yes-veggie-checkpoint1.glb','sha256':sha(ROOT/'yes-yes-veggie-checkpoint1.glb'),'note':'Earlier static build by the stopped run; rejected by the author concept comparison (flat jagged stalk shelf, pole under the top floret, smooth mushroom-cap florets, scale-like curd texture, trunk too wide, pointed generic leaves).'},
  'rebuild2_static':{'glb':'checkpoint-preview-rebuild2/yes-yes-veggie-checkpoint-rebuild2.glb','sha256':sha(ROOT/'checkpoint-preview-rebuild2/yes-yes-veggie-checkpoint-rebuild2.glb'),'note':'Early exact-export static rebuild before rigging clearance changes.'}},
 'source_scripts':{p.name:sha(p) for p in sorted(SOURCE.iterdir()) if p.suffix in ['.py','.mjs','.json']},
 'original_work':['Original broccoli geometry: voxel-merged stalk, feet and eleven thick branches, eleven lumpy florets, face, arms and cupped leaf mittens; all five clips.','Original deterministic 1024 indexed-palette atlas generated in Blender Python; soft occlusion ray-traced in Blender and stored as COLOR_0; no external texture.','Mesh, UV, transfer and validation utilities adapted from the WO111 gadget-helper and honk-bus and the Rat Casino authoring scripts.'],
 'excluded_inputs':['No family photos, names, birthdays or likenesses.','No copied franchise models, faces, logos, costumes, recordings or textures; no melon motifs, lettering, teeth or props.'],
 'rights_note':'Original generated concept and authored study. Generated media is not automatically relicensed under the repository code license; no exclusive-rights or franchise-endorsement claim.',
 'scope':'Technical candidate delivery. The coordinator owns catalog publication and runtime integration; owner exact-version and physical-device review remain open.'}
settings={**common,
 'blender':{'version':construction['blender_version'],'units':'METRIC','unit_scale':1,'authoring_axes':'+Z up / +Y forward (anatomical left = -X)','frames_per_second':60,'animation_mode':'NLA_TRACKS','skin':'One skin; stalk blends legs/hips/body/crown by height (legs split smoothly across the notch), arms blend body/arm/forearm/hand along the path, florets and face parts rigid','root':'Identity, fixed floor-centred root; no root animation; feet rest on the floor'},
 'export':{'format':'GLB','axes':'+Y up / -Z forward','selection_only':True,'materials':2,'texture':{'file':'pigment.png','width':1024,'height':1024,'embedded':True},'vertex_color':'COLOR_0 soft occlusion multiplier (active color attribute)','no_external_resources':True,'no_required_extensions':True,'compression':'None; no Draco, Meshopt or KTX2 requirement'},
 'preview':{'source':'Exact delivered GLB via Three.js GLTFLoader','three_revision':three['three_revision'],'browser':browser['browser'],'renderer':browser['renderer'],'viewport_px':[800,900],'orthographic_camera':{'left':-.6,'right':.6,'top':.675,'bottom':-.675,'target':[0,.52,0],'beauty_position':[3.1,1.52,-6]},'lighting':'Warm hemisphere plus three directional lights; ACES tone mapping exposure 1.0','scales':[1,.35],'no_physical_device_claim':True},
 'checks':{'khronos_zero_errors_warnings':True,'exact_three_adapter_all_checks':True,'chromium_all_clips_normal_small':True,'source_attachment_checks':True}}
visual={**common,
 'author_review':'Exact-export front, side, back and beauty stills compared with the concept FRONT/SIDE/BACK construction views and the three-quarter hero (concept-vs-export.png); five-clip normal/small motion sheets; attack front/side windup-contact-recovery; held defeat front/side/beauty inspected.',
 'coordinator_review':'Pending PLAN-019 coordinator intake. Not Tom approval.','owner_review':'Pending exact-version decision',
 'concept_matching':['Chunky yellow-lime stalk that splits into two bulbous feet with toe creases and, at the top, into thick branches separated by dark slits, as in the concept front and back views.','Broad dark-green crown about 0.75 m wide from about 0.52 m to 1.0 m, lumpy floret domes with painted curd bumps; low florets hang at the sides and back corners.','Big cream oval eyes with inward-glaring pupils and catchlights, thick dark brows tilted down to the middle, tiny pursed frown and warm cheeks.','Thin stalk arms from the stalk sides below the cheeks ending in broad cupped spinach-like leaf mittens at hip height.','Side view: crown centred behind the face with its front edge slightly ahead of it; the concept hero hands-on-hips pose is not the rest pose (the construction views are).'],
 'author_corrections':['Checkpoint 1 (earlier run) was rebuilt: its stalk ended in a flat, jagged shelf with a thin pole under the top floret; the trunk is now about 15% narrower, flares gradually and splits into eleven fat branches whose tips end inside their florets.','Florets enlarged about 10%, bottom flattening reduced (0.74 to 0.86) and lobes strengthened so the crown reads as one lumpy cloud instead of mushroom caps; a bottom-centre back floret was replaced by two low back-corner florets to match the concept back view.','Curd texture changed from Voronoi cell edges (read as scales) to lit round bumps grouped in crevice-edged clusters.','Soft occlusion baked into COLOR_0 so slits, floret crevices, the leg notch and foot contact read dark in three.js.','Stalk palette shifted greener after sampling the render (#d0cb69) against the concept (#dbde74); leaves lightened slightly.','Feet rounded and widened into bulbous shoes; leaves broadened with rounded shoulders and turned 34 degrees from the front.','Crotch weights split smoothly between both legs after the first motion review showed a torn flap at the notch during the lunge and a V pinch in the held defeat.','Contact pose changed from a lean-back belly bump to a forward lunge with the leaves thrust out beside the face after the first motion review showed contact reading too close to the warning.','Defeat arms flopped outward after the source audit found a 2.6 cm leaf/stalk overlap; rest wrists moved 9 mm outward after the audit found 0.3 mm rest clearance. Final minimum leaf/stalk clearance is 4.9 mm.'],
 'dimensions_width_height_depth_m':three['dimensions_m'],'rest_bounds_y_up':three['rest_bounds_y_up'],'animated_bounds_y_up':three['all_animation_bounds_y_up'],'stored_safe_culling_bounds':three['exported_safe_bounds_y_up'],'footprint_y_up':three['footprint_y_up'],
 'contact_seconds':contact['contact_time_s'],'attack_duration_seconds':contact['duration_s'],'measured_stable_warning_seconds':contact['held_warning_s'],'defeat_held_from_seconds':defeat['held_final_pose_from_s'],
 'no_floor_penetration':three['checks']['no_floor_penetration'],'defeat_lowest_leaf_tip_m':three['animations']['defeat']['minimum_leaf_tip_y_m'],'attachment_worst_margins_m':{k:v['margin_m'] for k,v in attachments['worst'].items()},
 'limitations':['Headless software Chromium is not physical Safari or hardware performance acceptance.','Attachment audit supplements the exact GLB all-vertex checks; it does not claim universal triangle collision testing.','The defeat is a planted squash-down sulk (hips drop 8.5 cm, feet splay); the leg-weighted lower stalk keeps the bottom above the floor rather than sitting flat.','Owner final-art review and runtime integration are separate from this authoring handoff.']}
bounds={**common,'method':three['method'],'rest_bounds_y_up':three['rest_bounds_y_up'],'dimensions_width_height_depth_m':three['dimensions_m'],'footprint_y_up':three['footprint_y_up'],'all_animation_bounds_y_up':three['all_animation_bounds_y_up'],'safe_culling_envelope_y_up':three['exported_safe_bounds_y_up'],'note':'glTF axes: +Y up, character faces -Z; anatomical left is -X. Root at the floor origin under the stalk centre; feet rest on the floor.'}
for name,record in [('provenance.json',provenance),('tool-settings.json',settings),('visual-review.json',visual),('bounds.json',bounds)]:
 (ROOT/name).write_text(json.dumps(record,indent=2)+'\n')
print(json.dumps({'glb_sha256':digest,'reports':['provenance.json','tool-settings.json','visual-review.json','bounds.json'],'all_technical_checks':True}))
