"""WO111 exact-byte authoring provenance and factual review handoff."""
from pathlib import Path
import json,hashlib,datetime
ROOT=Path('/home/dev/artifacts/haynes-quest/family-eras/honk-bus/v001')
SOURCE=Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
digest=sha(ROOT/'honk-bus.glb')
construction=json.loads((ROOT/'construction.json').read_text())
three=json.loads((ROOT/'three-inspection.json').read_text())
browser=json.loads((ROOT/'final-preview/browser-inspection.json').read_text())
validation=json.loads((ROOT/'validation.json').read_text())
attachments=json.loads((ROOT/'attachment-inspection.json').read_text())
for report in [three,browser,validation,attachments]:
 assert report.get('glb_sha256',report.get('sha256'))==digest
 assert all(report['checks'].values())
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
common={'work_order':'WO111','asset_id':'honk-bus','version':'v001','created_utc':now,'glb_sha256':digest,'candidate_status':"Awaiting Tom's review · used in the family release"}
provenance={**common,'authoring_agent':'Fresh native GPT-6 Astra subagent at max','authoring_tool':'Blender MCP execute_blender_code on the dedicated authoring service','blender_version':construction['blender_version'],'source_concept':{'file':'concept.png','sha256':sha(ROOT/'concept.png'),'source_record':'source.json','selection':'Driving Astra selected original generated concept; no franchise source media.'},'source_scripts':{p.name:sha(p) for p in sorted(SOURCE.iterdir()) if p.suffix in ['.py','.mjs','.json']},'original_work':['Original bus geometry, roof trumpet, face, suspension and all five clips.','Original deterministic 1024 palette atlas generated in Blender Python; no external texture.','Only tested mesh, UV, transfer and validation utilities adapted from prior authored characters.'],'excluded_inputs':['No family photos, names, birthdays or likenesses.','No copied franchise models, faces, logos, costumes, recordings or textures.'],'rights_note':'Original generated concept and authored study. Generated media is not automatically relicensed under the repository code license; no exclusive-rights or franchise-endorsement claim.','scope':'Technical candidate delivery. Lead owns catalog publication and runtime integration; owner exact-version and physical-device review remain open.'}
settings={**common,'blender':{'version':construction['blender_version'],'units':'METRIC','unit_scale':1,'authoring_axes':'+Z up / +Y forward','frames_per_second':60,'animation_mode':'NLA_TRACKS','skin':'One skin, attached rigid parts plus two-weight continuous horn support','root':'Identity, fixed floor-centered root; no root animation'},'export':{'format':'GLB','axes':'+Y up / -Z forward','selection_only':True,'materials':2,'texture':{'file':'pigment.png','width':1024,'height':1024,'embedded':True},'no_external_resources':True,'no_required_extensions':True,'compression':'None; no Draco, Meshopt or KTX2 requirement'},'preview':{'source':'Exact delivered GLB via Three.js GLTFLoader','three_revision':three['three_revision'],'browser':browser['browser'],'renderer':browser['renderer'],'viewport_px':[800,900],'orthographic_camera':{'left':-1.6,'right':1.6,'top':1.8,'bottom':-1.8,'target':[0,1.17,0],'beauty_position':[3.1,2.01,-6]},'lighting':'Warm hemisphere plus three directional lights; ACES tone mapping exposure 1.0','scales':[1,.35],'no_physical_device_claim':True},'checks':{'khronos_zero_errors_warnings':True,'exact_three_adapter_all_checks':True,'chromium_all_clips_normal_small':True,'source_attachment_checks':True}}
visual={**common,'author_review':'Front, side, back, beauty; five-clip normal/small motion sheets; attack front/side warning-contact-recovery; held defeat front/side/beauty inspected.','coordinator_review':'Lead accepted the final exact candidate after viewing rest beauty and held-defeat front, side and three-quarter, following accepted fender/trim and attack corrections. This is coordinator intake, not Tom approval.','owner_review':'Pending exact-version decision','construction_choices':['Preserved the chosen short chunky bus proportions rather than the prompt nominal 3.5m length.','Opaque windshield eyes and side/back windows, broad cream grin, amber headlights, plum tires and squeeze bulb.','Rounded seated fenders and no thin projecting roof-seam rods.','Fixed grounded axles and continuously connected suspension struts keep wheels attached through the body bounce.','Defeat lowers and rotates the brows; the continuous roof support extends as the trumpet tilts down 0.50 rad.','The first stronger-defeat audit found 7.16mm conservative fender/tire overlap; reducing only the stall sink removed it, with 7.95mm final clearance.'],'dimensions_width_height_depth_m':three['dimensions_m'],'animated_bounds_y_up':three['all_animation_bounds_y_up'],'stored_safe_culling_bounds':three['exported_safe_bounds_y_up'],'contact_seconds':1.25,'attack_duration_seconds':2.0,'measured_stable_warning_seconds':[.60,1.05],'defeat_held_from_seconds':1.666667,'minimum_horn_roof_clearance_m':three['minimum_horn_roof_clearance_m'],'minimum_fender_tire_clearance_m':min(c['minimum_fender_wheel_cylinder_clearance_m'] for c in attachments['clips'].values()),'no_floor_penetration':three['checks']['no_floor_penetration'],'limitations':['Headless software Chromium is not physical Safari or hardware performance acceptance.','Attachment audit supplements the exact GLB all-vertex checks; it does not claim universal triangle collision testing.','Owner final-art review and runtime integration are separate from this authoring handoff.']}
for name,record in [('provenance.json',provenance),('tool-settings.json',settings),('visual-review.json',visual)]:
 (ROOT/name).write_text(json.dumps(record,indent=2)+'\n')
print(json.dumps({'glb_sha256':digest,'reports':['provenance.json','tool-settings.json','visual-review.json'],'all_technical_checks':True}))
